[theme]
# Primary accent color for interactive elements.
primaryColor = "#FFFFE0"

# Background color for the main content area.
backgroundColor = "#FFFFE0"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#EEE8AA"

# Color used for almost all text.
textColor = "#556B2F"

# Font family for all text in the app, except code blocks. One of "serif", "serif", or "serif".
# Default: "serif"
font = "serif"

[global]
dataFrameSerialization = "legacy" 